package com.panshi.hujin2.message.domain.enums.getui;

/**
 * create by shenjiankang on 2018/9/28 18:14
 */
public enum GeTuiAppConfigEnum {


    //巴西
    //盘管家（记账管家）
    // Guiafatura
//    BR_MONEYMANAGER_APP_ID("BQVFf8LTjZ78jOchGxYKgA"),
//    BR_MONEYMANAGER_APP_SECRET("YGZrrJUGzRA0wXYrLyQNM2"),
//    BR_MONEYMANAGER_APP_KEY("2I0t7zD8kF6BwVqXeQHcA3"),
//    BR_MONEYMANAGER_MASTER_SECRET("Vy9nei13YY69Ev5ejZFye"),
//
//    //eLoan
//    BR_ELOAN_APP_ID("1Rj2h9kp4OAPgNlz55cQU1"),
//    BR_ELOAN_APP_SECRET("vyGHU55U68AKdkXAASeKz1"),
//    BR_ELOAN_APP_KEY("vyGHU55U68AKdkXAASeKz1"),
//    BR_ELOAN_MASTER_SECRET("t7tLg08dwA6P1mR3qhKnK8"),
//
//    //MyLoan
//    BR_MYLOAN_APP_ID("PpAzTAQfq96jaYOQHuf5t9"),
//    BR_MYLOAN_APP_SECRET("dncwEtpWGx8IVN9ffZSPf3"),
//    BR_MYLOAN_APP_KEY("2Qi3vXq14W9RU2NujKXZYA"),
//    BR_MYLOAN_MASTER_SECRET("YCot0QPqpv6OYLLkMEeSO6"),
//
//    //FlashLoan
//    BR_FLASHLOAN_APP_ID("rGf0xBYOBWATrYCw6knoC5"),
//    BR_FLASHLOAN_APP_SECRET("6sr7mvJfd57wb7eoUPhy15"),
//    BR_FLASHLOAN_APP_KEY("Wzty5kjoTQ6BWJGEa1Ey7A"),
//    BR_FLASHLOAN_MASTER_SECRET("APAGZlU9OQ8tIMQwFjHu97"),
//
//    //SimpleLoan
//    BR_SIMPLELOAN_APP_ID("0l6Y8OyJLA6UCii8vseB64"),
//    BR_SIMPLELOAN_APP_SECRET("jOKMXOe3wf6OpI4FXVdoP"),
//    BR_SIMPLELOAN_APP_KEY("H9kMmVVowI9AiLdEPAVSt2"),
//    BR_SIMPLELOAN_MASTER_SECRET("1oaYeEgUd96xpe4PHneR8"),
//
//    //WOWLoan
//    BR_WOWLOAN_APP_ID("WzzQ8oIEp88xzAkMztRU07"),
//    BR_WOWLOAN_APP_SECRET("n6GZA55uyc55FzTQzyiaL5"),
//    BR_WOWLOAN_APP_KEY("HxHtQqQmDm6gLlY0UvyJl2"),
//    BR_WOWLOAN_MASTER_SECRET("iu443oR25PAOnJp45CDma4"),
//
//    //FreeLoan
//    BR_FREELOAN_APP_ID("oSd8AVuSfE9SVD6NMKRUb3"),
//    BR_FREELOAN_APP_SECRET("4bHHoVPmIuAJC1RXb3vli2"),
//    BR_FREELOAN_APP_KEY("Z7jMlXhGl58oFGlUIiQhP3"),
//    BR_FREELOAN_MASTER_SECRET("g3F2NrQaey7ZTdmDV0Gze"),
//
//
//
//
//
//
//    //墨西哥
//    //moneyRush(eLoan 无忧贷)
//    MX_MONEYRUSH_APP_ID("xbw9LoCIWf5swdLhYe6gE5"),
//    MX_MONEYRUSH_APP_SECRET("SpMYpWv6Fr6oG63lpIvu97"),
//    MX_MONEYRUSH_APP_KEY("VX9nWn4kPm7Hl4C7F3PGn7"),
//    MX_MONEYRUSH_MASTER_SECRET("KSFJoQ9ue9ArHnY51dWYr7"),
//
//    //iLoan  暂时安卓前端没有配置
//    MX_ILOAN_APP_ID("GE4DVYJ8Wu5V2tC9BhNZZ9"),
//    MX_ILOAN_APP_SECRET("Y2lWq3EBQwAdHBVGnhH9Z9"),
//    MX_ILOAN_APP_KEY("ENXZKHQE3c83rU7JHBg7d5"),
//    MX_ILOAN_MASTER_SECRET("iBy5jQNsCt68F3XslIgnn6"),
//
//    //mLoan
//    MX_MLOAN_APP_ID("gcwPeA1Cn47Vs1ezmrQxF5"),
//    MX_MLOAN_APP_SECRET("zISd69sGEH8OMivLvLaXD4"),
//    MX_MLOAN_APP_KEY("ORpXZOeqKo5BtqMnckTab6"),
//    MX_MLOAN_MASTER_SECRET("94XdUY5qN98xFb9STTmUU5"),
//
//    //yLoan
//    MX_YLOAN_APP_ID("vxFSDIEoNp7uOZWEtUXih4"),
//    MX_YLOAN_APP_SECRET("BqIO5Qq2av9iDKHAyDsRP5"),
//    MX_YLOAN_APP_KEY("tkypZGNb4q9cHIDCnSQSQ"),
//    MX_YLOAN_MASTER_SECRET("afqr7mZsqSAUWQBcqv8RU6"),
//
//    //uLoan
//    MX_ULOAN_APP_ID("N3GmuLqCbb6XKqB7MV9xk8"),
//    MX_ULOAN_APP_SECRET("tFGFXDqZYc9O62fykBhP44"),
//    MX_ULOAN_APP_KEY("Yng6OOqqvP6PbauZyBatj5"),
//    MX_ULOAN_MASTER_SECRET("zIYpIX8Sdo89cd3Ta6Wim2"),
//
//    //MoneyR
//    MX_MONEYR_APP_ID("kmRHg1NvsR7qxiwRXjH2d2"),
//    MX_MONEYR_APP_SECRET("OkZjFrhuYY7t4K18m0aiP6"),
//    MX_MONEYR_APP_KEY("bPdhK1G6hy9mMdZzQKuDU5"),
//    MX_MONEYR_MASTER_SECRET("Oy3aZ4Vxog7dMPdzfUXwL6"),
//
//    //HiLoan
//    MX_HILOAN_APP_ID("Czzv3RhG3iA007bojJ9mz4"),
//    MX_HILOAN_APP_SECRET("sJnbZQd1gO7EhTjXvL1fB6"),
//    MX_HILOAN_APP_KEY("vvhW1N39bB7e3baaQV4v05"),
//    MX_HILOAN_MASTER_SECRET("0rHrnPXdgB9wCV9vxO6Qy3"),


    //越南貸超
    //旧包被下架了
//    VI_CASH_DOG_APP_ID("rAH1ndFMqN8jmsJzpfJq41"),
//    VI_CASH_DOG_APP_SECRET("ZjJWNug8B99u69nOCsNwJ1"),
//    VI_CASH_DOG_APP_KEY("g7iDXpLwAU7B8de29hLlZ6"),
//    VI_CASH_DOG_MASTER_SECRET("XmyxhQ9jzq9pLwk3D6GIB2"),
    //新包    com.cashdog1.newbeginning
    VI_CASH_DOG_APP_ID("HubnrkuybK9KjnwCzxdgE"),
    VI_CASH_DOG_APP_SECRET("JsASUIgCjx7X0GOsfFHW54"),
    VI_CASH_DOG_APP_KEY("BrWuv0dL7pA8xEkQqbhnU2"),
    VI_CASH_DOG_MASTER_SECRET("DYDqX10fxM6Nrh5J9iUQp3"),

    //印尼貸超
    INA_CASH_KANGAROO_APP_ID("mL5vYGD8CR74SWgnDrHO63"),
    INA_CASH_KANGAROO_APP_SECRET("Sy4qN6bzoN7nz6FUiUSDg2"),
    INA_CASH_KANGAROO_APP_KEY("rLX05roFWYAIugxsnLiLo6"),
    INA_CASH_KANGAROO_MASTER_SECRET("pmFsDUmwkY638SWPA1cB17"),

    //印尼貸超马甲2
    INA_CASH_KANGAROO_2_APP_ID("Anjw0UNRyW9aKlYHh5sHv7"),
    INA_CASH_KANGAROO_2_APP_SECRET("q9URA5l9s57TUdAJlxVkx5"),
    INA_CASH_KANGAROO_2_APP_KEY("fvz9eWCAZQ7tEKkU9l5ef"),
    INA_CASH_KANGAROO_2_MASTER_SECRET("trZEV2rH2y6boB9PDYqk03"),

    //印尼貸超马甲3
    INA_CASH_KANGAROO_DEXTER_APP_ID("wSgP5C64WV9Skiiw72BnU1"),
    INA_CASH_KANGAROO_DEXTER_APP_SECRET("2L5Q6IltQq89byPTx99HF9"),
    INA_CASH_KANGAROO_DEXTER_APP_KEY("BdHTR0SPjb5xolYK66mCu"),
    INA_CASH_KANGAROO_DEXTER_MASTER_SECRET("MQaMRi4jw66aBNEA3uiwN2"),

    //越南马甲包
    //下架的旧配置
//    VI_CASH_DOG_NEVERSOLDOUT_APP_ID("lxyjSqpfAz91a16gROfhC7"),
//    VI_CASH_DOG_NEVERSOLDOUT_APP_SECRET("XB0ieJjOKWA5XGSSHQ7PT9"),
//    VI_CASH_DOG_NEVERSOLDOUT_APP_KEY("jlJYsUJBnb6Pj8YAE1YgV2"),
//    VI_CASH_DOG_NEVERSOLDOUT_MASTER_SECRET("Tirij03dMc5pGeAFzP8Bt3"),

    //包com.onlineonemonth.dogcash新配置
    VI_CASH_DOG_NEVERSOLDOUT_APP_ID("gCoOej9c5mAtXyH4JN6Nw8"),
    VI_CASH_DOG_NEVERSOLDOUT_APP_SECRET("x0YISqiSTE75xBWnEB7TP"),
    VI_CASH_DOG_NEVERSOLDOUT_APP_KEY("LHosq1FxOa75wOOU65hX48"),
    VI_CASH_DOG_NEVERSOLDOUT_MASTER_SECRET("YsFPzhKR2EACGUOcZX9RD6"),

    //越南马甲包
    VI_CASH_DOG_GOODDAY_APP_ID("nPaFAk1xjI6wMnNMJ37mF6"),
    VI_CASH_DOG_GOODDAY_APP_SECRET("SMgMaV7eToAxQ3QGSB0jB2"),
    VI_CASH_DOG_GOODDAY_APP_KEY("YbznJMZZou86Nhlu0FEWL4"),
    VI_CASH_DOG_GOODDAY_MASTER_SECRET("dhyUAGHwAA95KIoG2JMgj4"),

    //越南马甲包28
    VI_CASH_CAT_APP_ID("9oPxNj76ck8npcBPfn04L9"),
    VI_CASH_CAT_APP_SECRET("2k18dOmSWX5ldOfvx4bW5A"),
    VI_CASH_CAT_APP_KEY("F2QamQeHpb9gAvtSIKIeT6"),
    VI_CASH_CAT_MASTER_SECRET("7IQhtxQTB87bj3AGnsjLz"),

    //越南马甲包29
    VI_IN_CASHCAT_APP_ID("NNAbIemMtI9zDxOp2ZDek3"),
    VI_IN_CASHCAT_APP_SECRET("Lxt3ndfyq19GY7w2xl3au9"),
    VI_IN_CASHCAT_APP_KEY("PpPgV3xT3GAy9Rcrb1kwF3"),
    VI_IN_CASHCAT_MASTER_SECRET("sm8PWPcIfT8EGAwEOv6gR5"),

    //印尼马甲包30
    INA_ATTRACTIVE_KANGAROOCASH_APP_ID("KnfD4qTV5t630ss4bOLaP6"),
    INA_ATTRACTIVE_KANGAROOCASH_APP_SECRET("GSnUT2yLpT9n5zJQpbN8e4"),
    INA_ATTRACTIVE_KANGAROOCASH_APP_KEY("FGky341m116UN9w3vfKIz4"),
    INA_ATTRACTIVE_KANGAROOCASH_MASTER_SECRET("PDgKb19ofe9iwT9SUSCt09"),

    //印尼马甲包31
    INA_KAS_KANGAROO_APP_ID("OpMZnpJ5KdAl0BE9W3uD0A"),
    INA_KAS_KANGAROO_APP_SECRET("1x9m20zLNH8dK3qmmOF4VA"),
    INA_KAS_KANGAROO_APP_KEY("0jKYn5s5lK8Mrt815XvSe"),
    INA_KAS_KANGAROO_MASTER_SECRET("DYxityuGLr6X31kkCS2AL8"),


    //越南马甲包32
//    VI_IN_CASHCAT_ENDORPHIN_APP_ID("539JcC7yuP9S30X9hsGON8"),
//    VI_IN_CASHCAT_ENDORPHIN_APP_SECRET("ihfnZfwUq76HjWNe21aGm2"),
//    VI_IN_CASHCAT_ENDORPHIN_APP_KEY("nFDvgY36Fi68OndX9ROce8"),
//    VI_IN_CASHCAT_ENDORPHIN_MASTER_SECRET("B4x81JWetH9cDtFqMN4c1"),
    VI_IN_CASHCAT_ENDORPHIN_APP_ID("cEway6ejHr71uS8wJ806c5"),
    VI_IN_CASHCAT_ENDORPHIN_APP_SECRET("ZOPiq7dKgS6WC9jaWuc8C6"),
    VI_IN_CASHCAT_ENDORPHIN_APP_KEY("iRk2gj9mzOAIT5IC2vVmw5"),
    VI_IN_CASHCAT_ENDORPHIN_MASTER_SECRET("Nm29axMTYz62P1Ab6eAFl8"),

    INA_KAS_INS_APP_ID("lHgHsbGlMJ7ysalP4iwo15"),
    INA_KAS_INS_APP_SECRET("Tobie8Eg4V6gHMREb4A5F4"),
    INA_KAS_INS_APP_KEY("NfVHywb11x8JpPtwKxGJn6"),
    INA_KAS_INS_MASTER_SECRET("LtJxXp3sS79140tth6WmlA"),

    // 印尼新马甲
    NEW_INA_CASH_KLICK_APP_ID("cLq5saDmNk9OQRQh2338f6"),
    NEW_INA_CASH_KLICK_APP_SECRET("lhfeILlUydASuGMq57X6n1"),
    NEW_INA_CASH_KLICK_APP_KEY("bmo0DSkq3X7AFalnZ5uta8"),
    NEW_INA_CASH_KLICK_MASTER_SECRET("zcrzZd5Yx78KPra75TAma9"),

    NEW_INA_CASH_MAS_APP_ID("KEkc6ISEIC6HlA8Vc1Buk6"),
    NEW_INA_CASH_MAS_APP_SECRET("mp8perPnkZ92OMhGVV2yp"),
    NEW_INA_CASH_MAS_APP_KEY("viDD5tnHnd7ABNnt9Zeq69"),
    NEW_INA_CASH_MAS_MASTER_SECRET("pvpyKjpzj76ebDQDJUP2V1"),

    // 203
    NEW_INA_CASH_KLICK_TASK_APP_ID("cLq5saDmNk9OQRQh2338f6"),
    NEW_INA_CASH_KLICK_TASK_APP_SECRET("lhfeILlUydASuGMq57X6n1"),
    NEW_INA_CASH_KLICK_TASK_APP_KEY("bmo0DSkq3X7AFalnZ5uta8"),
    NEW_INA_CASH_KLICK_TASK_MASTER_SECRET("zcrzZd5Yx78KPra75TAma9"),

    // 204
    NEW_INA_CASH_MAS_TEXT_APP_ID("Yhr18IQ1hr9zY4m6Ijgfm1"),
    NEW_INA_CASH_MAS_TEXT_APP_SECRET("ILLfLN3KiL8BIpZWJ9Df77"),
    NEW_INA_CASH_MAS_TEXT_APP_KEY("4CmovndIYn7EjxEoMwzgiA"),
    NEW_INA_CASH_MAS_TEXT_MASTER_SECRET("sXhPutQYhA94hs6cHUqhn3"),

    // 205
    NEW_INA_CASH_MASTEXT_UNNDT_APP_ID("Yhr18IQ1hr9zY4m6Ijgfm1"),
    NEW_INA_CASH_MASTEXT_UNNDT_APP_SECRET("ILLfLN3KiL8BIpZWJ9Df77"),
    NEW_INA_CASH_MASTEXT_UNNDT_APP_KEY("4CmovndIYn7EjxEoMwzgiA"),
    NEW_INA_CASH_MASTEXT_UNNDT_MASTER_SECRET("sXhPutQYhA94hs6cHUqhn3"),


    // 206
    NEW_INA_CASH_TASK_WQAS_APP_ID("cLq5saDmNk9OQRQh2338f6"),
    NEW_INA_CASH_TASK_WQAS_APP_SECRET("lhfeILlUydASuGMq57X6n1"),
    NEW_INA_CASH_TASK_WQAS_APP_KEY("bmo0DSkq3X7AFalnZ5uta8"),
    NEW_INA_CASH_TASK_WQAS_MASTER_SECRET("zcrzZd5Yx78KPra75TAma9"),

    INA_KASROO_APP_ID("DNlDAVzXBp8yJPiG0fEao3"),
    INA_KASROO_APP_SECRET("UgmERvZu6x7FF5owvasSP1"),
    INA_KASROO_APP_KEY("BDneXwLwut9z2f12dwYoCA"),
    INA_KASROO_MASTER_SECRET("szdXD2dC6i5hWl7obikco5"),

    // 500
    INA_CASH_YINNI_IN_APP_ID("QJiZcucO2ZA976w0hDEAY8"),
    INA_CASH_YINNI_IN_APP_SECRET("jR7CZxcxRk8qsWoeD2NVt5"),
    INA_CASH_YINNI_IN_APP_KEY("qIz3mLZN5S9VqFmJr3RKA6"),
    INA_CASH_YINNI_IN_MASTER_SECRET("ua4QMaD8na86XJUJaX6iq7"),



    // 600
    VI_CASH_ANDROID_CASHCAT_APP_ID("DNlDAVzXBp8yJPiG0fEao3"),
    VI_CASH_ANDROID_CASHCAT_APP_SECRET("UgmERvZu6x7FF5owvasSP1"),
    VI_CASH_ANDROID_CASHCAT_APP_KEY("BDneXwLwut9z2f12dwYoCA"),
    VI_CASH_ANDROID_CASHCAT_MASTER_SECRET("szdXD2dC6i5hWl7obikco5"),


    ;



    private String value;

    GeTuiAppConfigEnum(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
