package com.panshi.hujin2.message.domain.enums.getui;

/**
 * create by shenjiankang on 2018/9/28 18:14
 */
public enum GeTuiAppConfigEnum {


    //巴西
    //盘管家（记账管家）
    // Guiafatura
    BR_MONEYMANAGER_APP_ID("BQVFf8LTjZ78jOchGxYKgA"),
    BR_MONEYMANAGER_APP_SECRET("YGZrrJUGzRA0wXYrLyQNM2"),
    BR_MONEYMANAGER_APP_KEY("2I0t7zD8kF6BwVqXeQHcA3"),
    BR_MONEYMANAGER_MASTER_SECRET("Vy9nei13YY69Ev5ejZFye"),

    //eLoan
    BR_ELOAN_APP_ID("1Rj2h9kp4OAPgNlz55cQU1"),
    BR_ELOAN_APP_SECRET("vyGHU55U68AKdkXAASeKz1"),
    BR_ELOAN_APP_KEY("vyGHU55U68AKdkXAASeKz1"),
    BR_ELOAN_MASTER_SECRET("t7tLg08dwA6P1mR3qhKnK8"),

    //MyLoan
    BR_MYLOAN_APP_ID("PpAzTAQfq96jaYOQHuf5t9"),
    BR_MYLOAN_APP_SECRET("dncwEtpWGx8IVN9ffZSPf3"),
    BR_MYLOAN_APP_KEY("2Qi3vXq14W9RU2NujKXZYA"),
    BR_MYLOAN_MASTER_SECRET("YCot0QPqpv6OYLLkMEeSO6"),

    //FlashLoan
    BR_FLASHLOAN_APP_ID("rGf0xBYOBWATrYCw6knoC5"),
    BR_FLASHLOAN_APP_SECRET("6sr7mvJfd57wb7eoUPhy15"),
    BR_FLASHLOAN_APP_KEY("Wzty5kjoTQ6BWJGEa1Ey7A"),
    BR_FLASHLOAN_MASTER_SECRET("APAGZlU9OQ8tIMQwFjHu97"),

    //SimpleLoan
    BR_SIMPLELOAN_APP_ID("0l6Y8OyJLA6UCii8vseB64"),
    BR_SIMPLELOAN_APP_SECRET("jOKMXOe3wf6OpI4FXVdoP"),
    BR_SIMPLELOAN_APP_KEY("H9kMmVVowI9AiLdEPAVSt2"),
    BR_SIMPLELOAN_MASTER_SECRET("1oaYeEgUd96xpe4PHneR8"),

    //WOWLoan
    BR_WOWLOAN_APP_ID("WzzQ8oIEp88xzAkMztRU07"),
    BR_WOWLOAN_APP_SECRET("n6GZA55uyc55FzTQzyiaL5"),
    BR_WOWLOAN_APP_KEY("HxHtQqQmDm6gLlY0UvyJl2"),
    BR_WOWLOAN_MASTER_SECRET("iu443oR25PAOnJp45CDma4"),

    //FreeLoan
    BR_FREELOAN_APP_ID("oSd8AVuSfE9SVD6NMKRUb3"),
    BR_FREELOAN_APP_SECRET("4bHHoVPmIuAJC1RXb3vli2"),
    BR_FREELOAN_APP_KEY("Z7jMlXhGl58oFGlUIiQhP3"),
    BR_FREELOAN_MASTER_SECRET("g3F2NrQaey7ZTdmDV0Gze"),






    //墨西哥
    //moneyRush(eLoan 无忧贷)
    MX_MONEYRUSH_APP_ID("xbw9LoCIWf5swdLhYe6gE5"),
    MX_MONEYRUSH_APP_SECRET("SpMYpWv6Fr6oG63lpIvu97"),
    MX_MONEYRUSH_APP_KEY("VX9nWn4kPm7Hl4C7F3PGn7"),
    MX_MONEYRUSH_MASTER_SECRET("KSFJoQ9ue9ArHnY51dWYr7"),

    //iLoan  暂时安卓前端没有配置
    MX_ILOAN_APP_ID("GE4DVYJ8Wu5V2tC9BhNZZ9"),
    MX_ILOAN_APP_SECRET("Y2lWq3EBQwAdHBVGnhH9Z9"),
    MX_ILOAN_APP_KEY("ENXZKHQE3c83rU7JHBg7d5"),
    MX_ILOAN_MASTER_SECRET("iBy5jQNsCt68F3XslIgnn6"),

    //mLoan
    MX_MLOAN_APP_ID("gcwPeA1Cn47Vs1ezmrQxF5"),
    MX_MLOAN_APP_SECRET("zISd69sGEH8OMivLvLaXD4"),
    MX_MLOAN_APP_KEY("ORpXZOeqKo5BtqMnckTab6"),
    MX_MLOAN_MASTER_SECRET("94XdUY5qN98xFb9STTmUU5"),

    //yLoan
    MX_YLOAN_APP_ID("vxFSDIEoNp7uOZWEtUXih4"),
    MX_YLOAN_APP_SECRET("BqIO5Qq2av9iDKHAyDsRP5"),
    MX_YLOAN_APP_KEY("tkypZGNb4q9cHIDCnSQSQ"),
    MX_YLOAN_MASTER_SECRET("afqr7mZsqSAUWQBcqv8RU6"),

    //uLoan
    MX_ULOAN_APP_ID("N3GmuLqCbb6XKqB7MV9xk8"),
    MX_ULOAN_APP_SECRET("tFGFXDqZYc9O62fykBhP44"),
    MX_ULOAN_APP_KEY("Yng6OOqqvP6PbauZyBatj5"),
    MX_ULOAN_MASTER_SECRET("zIYpIX8Sdo89cd3Ta6Wim2"),

    //MoneyR
    MX_MONEYR_APP_ID("kmRHg1NvsR7qxiwRXjH2d2"),
    MX_MONEYR_APP_SECRET("OkZjFrhuYY7t4K18m0aiP6"),
    MX_MONEYR_APP_KEY("bPdhK1G6hy9mMdZzQKuDU5"),
    MX_MONEYR_MASTER_SECRET("Oy3aZ4Vxog7dMPdzfUXwL6"),

    //HiLoan
    MX_HILOAN_APP_ID("Czzv3RhG3iA007bojJ9mz4"),
    MX_HILOAN_APP_SECRET("sJnbZQd1gO7EhTjXvL1fB6"),
    MX_HILOAN_APP_KEY("vvhW1N39bB7e3baaQV4v05"),
    MX_HILOAN_MASTER_SECRET("0rHrnPXdgB9wCV9vxO6Qy3"),


    //越南貸超
    VI_CASH_DOG_APP_ID("rAH1ndFMqN8jmsJzpfJq41"),
    VI_CASH_DOG_APP_SECRET("ZjJWNug8B99u69nOCsNwJ1"),
    VI_CASH_DOG_APP_KEY("g7iDXpLwAU7B8de29hLlZ6"),
    VI_CASH_DOG_MASTER_SECRET("XmyxhQ9jzq9pLwk3D6GIB2"),

    //印尼貸超
    INA_CASH_KANGAROO_APP_ID("mL5vYGD8CR74SWgnDrHO63"),
    INA_CASH_KANGAROO_APP_SECRET("Sy4qN6bzoN7nz6FUiUSDg2"),
    INA_CASH_KANGAROO_APP_KEY("rLX05roFWYAIugxsnLiLo6"),
    INA_CASH_KANGAROO_MASTER_SECRET("pmFsDUmwkY638SWPA1cB17"),

            ;



    private String value;

    GeTuiAppConfigEnum(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
